export const academicQuestions = {
  data: [
    {
      questionNumber: "1",
      question: "What is the primary purpose of critical reading?",
      options: {
        a: "To read for pleasure only",
        b: "To understand and evaluate the text",
        c: "To memorize facts without understanding",
        d: "To find fault with the author",
        e: "To read as quickly as possible",
      },
      id: "q1",
    },
    {
      questionNumber: "2",
      question: "A critical reader is one who...",
      options: {
        a: "Believes everything they read",
        b: "Asks questions and analyzes the text",
        c: "Reads only the first and last pages",
        d: "Ignores the author's purpose",
        e: "Focuses only on the pictures",
      },
      id: "q2",
    },
    {
      questionNumber: "3",
      question: "The first step in the critical reading process is often...",
      options: {
        a: "Writing a summary",
        b: "Surveying or previewing the text",
        c: "Reading the text line by line",
        d: "Memorizing the conclusion",
        e: "Criticizing the author",
      },
      id: "q3",
    },
    {
      questionNumber: "4",
      question: "Evaluating information while reading means...",
      options: {
        a: "Agreeing with the author on all points",
        b: "Judging the credibility and value of the information",
        c: "Counting the number of paragraphs",
        d: "Learning new vocabulary only",
        e: "Reading the text aloud",
      },
      id: "q4",
    },
    {
      questionNumber: "5",
      question: "Which of the following is a statement of fact?",
      options: {
        a: "Mathematics is the hardest subject.",
        b: "English is more interesting than French.",
        c: "The sun rises from the east.",
        d: "The best food is pounded yam.",
        e: "Blue is the most beautiful colour.",
      },
      id: "q5",
    },
    {
      questionNumber: "6",
      question: "An opinion is a statement that...",
      options: {
        a: "Can be proven to be true or false",
        b: "Is based on scientific law",
        c: "Reflects a personal belief or feeling",
        d: "Is found in an encyclopedia",
        e: "Is always correct",
      },
      id: "q6",
    },
    {
      questionNumber: "7",
      question: '"Lagos is the best city in Nigeria." This statement is an...',
      options: {
        a: "Opinion",
        b: "Fact",
        c: "Undeniable truth",
        d: "Scientific theory",
        e: "Historical record",
      },
      id: "q7",
    },
    {
      questionNumber: "8",
      question:
        'When reading an article about the "evils of smoking", a critical reader should...',
      options: {
        a: "Accept all claims without question",
        b: "Differentiate between the proven facts and the author's opinions",
        c: "Focus only on the writer's feelings",
        d: "Ignore the scientific evidence presented",
        e: "Assume the writer is wrong",
      },
      id: "q8",
    },
    {
      questionNumber: "9",
      question: "Skimming is a reading technique used to...",
      options: {
        a: "Understand every single detail",
        b: "Get a general overview or gist of a text",
        c: "Read a text word for word",
        d: "Analyze the grammar of a passage",
        e: "Memorize the text completely",
      },
      id: "q9",
    },
    {
      questionNumber: "10",
      question: "You would most likely skim a newspaper to...",
      options: {
        a: "Decide which articles you want to read in full",
        b: "Understand the chemical composition of the paper",
        c: "Practice your pronunciation",
        d: "Analyze the writer's style in depth",
        e: "Find a specific date",
      },
      id: "q10",
    },
    {
      questionNumber: "11",
      question: "Scanning is used when you are looking for...",
      options: {
        a: "The main idea of a passage",
        b: "The author's opinion",
        c: "A specific piece of information, like a name or date",
        d: "The overall mood of the text",
        e: "Grammatical errors",
      },
      id: "q11",
    },
    {
      questionNumber: "12",
      question: "Which of these tasks would be best accomplished by scanning?",
      options: {
        a: "Understanding the plot of a novel",
        b: "Finding a phone number in a directory",
        c: "Appreciating the beauty of a poem",
        d: "Writing a critical review of a book",
        e: "Getting the general theme of an essay",
      },
      id: "q12",
    },
    {
      questionNumber: "13",
      question: "A good summary should...",
      options: {
        a: "Be longer than the original text",
        b: "Include the reader's personal opinions",
        c: "Contain only the key ideas of the passage",
        d: "Copy the original text word-for-word",
        e: "Focus on minor examples and jokes",
      },
      id: "q13",
    },
    {
      questionNumber: "14",
      question: "The first step in writing a summary is to...",
      options: {
        a: "Write your own introduction",
        b: "Identify the topic sentences and main ideas",
        c: "Add details that are not in the passage",
        d: "Find a new title for the passage",
        e: "Copy the first and last paragraphs only",
      },
      id: "q14",
    },
    {
      questionNumber: "15",
      question:
        "Expressions like 'in conclusion', 'in short', and 'to sum up' often signal...",
      options: {
        a: "The introduction of a new idea",
        b: "A supporting detail",
        c: "A redirection of attention to the main points",
        d: "The author's biography",
        e: "An example",
      },
      id: "q15",
    },
    {
      questionNumber: "16",
      question:
        "Unnecessary details that should be left out of a summary include...",
      options: {
        a: "The main points",
        b: "The topic sentence",
        c: "Repetitions, examples, and minor details",
        d: "The author's central argument",
        e: "The conclusion of the passage",
      },
      id: "q16",
    },
    {
      questionNumber: "17",
      question:
        "When a question asks you to make an 'inference' or 'deduction' from a passage, you should...",
      options: {
        a: "Find the answer stated directly in the text",
        b: "Use clues from the text to arrive at a logical conclusion",
        c: "Guess the answer without reading",
        d: "Give your personal opinion on the topic",
        e: "Choose the longest option",
      },
      id: "q17",
    },
    {
      questionNumber: "18",
      question:
        "What is the best strategy for answering questions based on a passage?",
      options: {
        a: "Answer the questions from memory before reading",
        b: "Read the questions first to know what to look for",
        c: "Read only the passage and ignore the questions",
        d: "Choose answers that have familiar words",
        e: "Select the answer that appears first in the passage",
      },
      id: "q18",
    },
    {
      questionNumber: "19",
      question: "'Interpretation level' questions require the reader to...",
      options: {
        a: "Find a specific fact",
        b: "Explain the meaning of what is stated in the passage",
        c: "Recall information",
        d: "Project future outcomes",
        e: "State the author's name",
      },
      id: "q19",
    },
    {
      questionNumber: "20",
      question: "When answering questions from a passage, it is crucial to...",
      options: {
        a: "Make up your own story",
        b: "Base your answers solely on the information given in the passage",
        c: "Write answers that are as long as possible",
        d: "Disagree with the passage",
        e: "Use information from other books",
      },
      id: "q20",
    },
  ],
};
